Better nodetool (#36)
* Better nodetool discovery

diff --git a/config/REPLACE_WITH_ORG_NAME/service_checks.yml b/config/REPLACE_WITH_ORG_NAME/service_checks.yml
--- a/config/REPLACE_WITH_ORG_NAME/service_checks.yml
+++ b/config/REPLACE_WITH_ORG_NAME/service_checks.yml
@@ -8,8 +8,8 @@
 axonops_shell_check:
 
 - name: Check for schema disagreement
-  interval: 5m
-  timeout: 1m
+  interval: 15m
+  timeout: 2m
   shell: /bin/bash
   present: true
   script: |-
@@ -17,7 +17,19 @@ axonops_shell_check:
     EXIT_WARNING=1
     EXIT_CRITICAL=2
 
-    NODETOOL=/path/to/nodetool # REPLACE PATH TO nodetool
+    if type nodetool >/dev/null; then
+        NODETOOL=nodetool
+    elif [ -x /opt/cassandra/bin/nodetool ]; then
+        NODETOOL=/opt/cassandra/bin/nodetool
+    elif [ -x /usr/local/cassandra/bin/nodetool ]; then
+        NODETOOL=/usr/local/cassandra/bin/nodetool
+    else
+        echo "nodetool not found"
+        exit $EXIT_CRITICAL
+    fi
+    
+    # Sleep up to 60 seconds to avoid simultaneous checks
+    sleep $(shuf -i 1-60 -n 1)
 
     schema_variations=$($NODETOOL gossipinfo | grep SCHEMA | grep -vi UNREACHABLE | sed -e 's/SCHEMA:[0-9]*://g' | uniq | wc -l)
     if [ $? -gt 0 ]; then
@@ -31,8 +43,8 @@ axonops_shell_check:
     fi
 
 - name: Check for node DOWN
-  interval: 30s
-  timeout: 1m
+  interval: 15m
+  timeout: 2m
   shell: /bin/bash
   present: true
   script: |-
@@ -40,9 +52,22 @@ axonops_shell_check:
     EXIT_WARNING=1
     EXIT_CRITICAL=2
 
-    NODETOOL=/path/to/nodetool # REPLACE PATH TO nodetool
     WARNING_DN_COUNT=1
     CRITICAL_DN_COUNT=2
+
+    if type nodetool >/dev/null; then
+        NODETOOL=nodetool
+    elif [ -x /opt/cassandra/bin/nodetool ]; then
+        NODETOOL=/opt/cassandra/bin/nodetool
+    elif [ -x /usr/local/cassandra/bin/nodetool ]; then
+        NODETOOL=/usr/local/cassandra/bin/nodetool
+    else
+        echo "nodetool not found"
+        exit $EXIT_CRITICAL
+    fi
+    
+    # Sleep up to 60 seconds to avoid simultaneous checks
+    sleep $(shuf -i 1-60 -n 1)
 
     # Get the local Data Center from 'nodetool info'
     local_dc=$($NODETOOL info | awk -F: '/Data Center/{gsub(/^[ \t]+/, "", $2); print $2}')
